spring:
  profiles:
    active:
    - dev
---
spring:
  profiles:
    active: dev
  
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-client
server:
  port: 8203
